name: runpy
on:
  workflow_dispatch:
  # push:
  #   branches: 
  #     - master
  schedule:
    - cron:  '0/10 * * * *'
jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: pip install requests
      - run: python get_bing_video.py
      
      - name: Push new runs
        run: |
          git config --local user.email "renqiang06@126.com"
          git config --local user.name "renqiang06"
          git add .
          git commit -m 'docs: update runs' || echo "ignore commit failure, proceed"
          git push || echo "nothing to push" 
          