name: runpy
on:
  # workflow_dispatch:
  schedule:
    # IMPORTANT: Set cron job in UTC timezone
    - cron:  '0 0/5 * * *'
jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: pip install requests
      - run: python get_bing_video.py

      - name: Automerge
        uses: 'pascalgn/automerge-action@v0.14.3'
        env:
          GITHUB_TOKEN: '${{ secrets.ACT_TOKEN }}'
          MERGE_LABELS: ''
          # 只要是 renqiang06 用户，都进行合并
          MERGE_FILTER_AUTHOR: 'renqiang06'
